---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: cookbook_ci

platforms:
  - name: windows2012r2_chef12
    driver:
      box_url: <%= ENV['WINDOWS_BOX_URL'] %>
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      - recipe[beyondcompare]
    attributes:
      beyondcompare:
        base_url: <%= ENV['BEYONDCOMPARE_DOWNLOAD_URL'] %>
